-- ============================================
-- Smart Error Archiver Schema V5.9 (Production Hardened & Audit Ready)
-- ============================================

-- [P0-FIX] Supabase 部署最佳实践:
-- 扩展安装在 extensions schema，search_path 包含 extensions
SET search_path = public, extensions;

-- ============================================
-- 0. 必需扩展 (Required Extensions)
-- ============================================
-- [P0-FIX] 扩展安装到 extensions schema，避免污染 public
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- ============================================
-- 1. 基础工具 (Foundation)
-- ============================================

-- [P2-FIX] 删除无用序列 (review_settings 已使用 IDENTITY)
-- CREATE SEQUENCE IF NOT EXISTS public.review_settings_id_seq; -- REMOVED

-- 通用 updated_at 触发器函数
CREATE OR REPLACE FUNCTION public.handle_updated_at() 
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;

-- [V5.1] ENUM Definitions (Type Safety & Performance)
-- [P0-4] Idempotent creation across environments
DO $$ BEGIN
    CREATE TYPE public.question_type_enum AS ENUM ('choice', 'fill_blank', 'short_answer');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.difficulty_enum AS ENUM ('easy', 'medium', 'hard');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.exam_mode_enum AS ENUM ('exam', 'practice');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.exam_status_enum AS ENUM ('in_progress', 'completed', 'abandoned');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.answer_mode_enum AS ENUM ('online', 'paper');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.job_status_enum AS ENUM ('queued', 'running', 'partial', 'done', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.import_file_type_enum AS ENUM ('csv', 'xlsx', 'json', 'pdf');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.mgmt_op_type_enum AS ENUM ('merge', 'delete');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE public.mgmt_entity_type_enum AS ENUM ('subject', 'tag');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- [V5.3] FSRS 权重归档表 (Content-Addressable Storage)
-- 目的: 1. 100% 还原历史参数 2. 全局去重 (不同用户使用相同权重只存一份)
CREATE TABLE public.fsrs_configs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hash TEXT UNIQUE NOT NULL,      -- [P1-1] sha256 content hash (64 chars)
    weights JSONB NOT NULL,         -- 原始权重数据 [0.1, 0.2, ...]
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    -- [V5.3 Security] 权重长度校验
    CONSTRAINT fsrs_configs_weights_check CHECK (
        jsonb_typeof(weights) = 'array' AND jsonb_array_length(weights) = 21
    ),
    
    -- [P1-1 Data Integrity] 确保哈希与权重自洽，防止脏数据注入 (Using sha256)
    -- 注意: hash 基于 JSONB 规范化后的 text (key 排序 & 统一数值格式)，确保哈希稳定性
    CONSTRAINT fsrs_configs_hash_self_consistency CHECK (
        hash = encode(extensions.digest(weights::text, 'sha256'), 'hex')
    ),
    
    -- [P1-1 FIX] 样式/长度强约束，防止脏数据注入
    CONSTRAINT fsrs_configs_hash_format_check CHECK (hash ~ '^[0-9a-f]{64}$')
);

COMMENT ON TABLE public.fsrs_configs IS 'Deduplicated FSRS parameter configurations for full historical restoration';

-- [V5.4] 权重表权限收口：禁止公有访问
REVOKE ALL ON public.fsrs_configs FROM PUBLIC;
REVOKE ALL ON public.fsrs_configs FROM anon, authenticated;

-- [P0-3] 确保表物理不可变：内容寻址系统严禁修改或删除
CREATE OR REPLACE FUNCTION public.prevent_modification_on_fsrs_configs()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Updates or Deletes are not allowed on fsrs_configs (Content-Addressed Table)';
END $$;

CREATE TRIGGER trg_fsrs_configs_no_mod
BEFORE UPDATE OR DELETE ON public.fsrs_configs
FOR EACH ROW EXECUTE FUNCTION public.prevent_modification_on_fsrs_configs();

-- ============================================
-- 2. 核心表结构 (Tables)
-- ============================================

-- 2.1 学科 (Subjects)
CREATE TABLE public.subjects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    color TEXT DEFAULT '#1976d2'::text,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    deleted_at TIMESTAMPTZ -- [V5.6 Soft Delete]
);
-- 唯一性与索引
-- [V5.6 Conditional Unique] 支持删除后名称重用
CREATE UNIQUE INDEX IF NOT EXISTS uq_subjects_global_name ON public.subjects(name) WHERE user_id IS NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_subjects_user_name ON public.subjects(user_id, name) WHERE user_id IS NOT NULL AND deleted_at IS NULL;
-- [V5.5 Performance] 加速 RLS 过滤
CREATE INDEX IF NOT EXISTS idx_subjects_user_id ON public.subjects(user_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_subjects_updated BEFORE UPDATE ON public.subjects FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;

-- 2.2 标签 (Tags)
CREATE TABLE public.tags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    color TEXT DEFAULT '#00bcd4'::text,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    deleted_at TIMESTAMPTZ -- [V5.6 Soft Delete]
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tags_global_name ON public.tags(name) WHERE user_id IS NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_tags_user_name ON public.tags(user_id, name) WHERE user_id IS NOT NULL AND deleted_at IS NULL;
-- [V5.5 Performance] 加速 RLS 过滤
CREATE INDEX IF NOT EXISTS idx_tags_user_id ON public.tags(user_id) WHERE deleted_at IS NULL;
CREATE TRIGGER trg_tags_updated BEFORE UPDATE ON public.tags FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

-- 2.3 错题 (Error Questions)
CREATE TABLE public.error_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- 核心内容
    title TEXT NOT NULL,
    content TEXT,
    question_type public.question_type_enum NOT NULL, -- [P2-3] Use ENUM
    difficulty public.difficulty_enum NOT NULL DEFAULT 'medium'::public.difficulty_enum, -- [P2-3] Use ENUM
    
    explanation TEXT,
    
    -- 资源
    correct_answer_image_url TEXT,
    explanation_image_url TEXT,
    image_url TEXT,
    
    -- 元数据
    hints JSONB DEFAULT '{}'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    
    -- 归属
    subject_id UUID REFERENCES public.subjects(id) ON DELETE SET NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    forked_from UUID REFERENCES public.error_questions(id) ON DELETE SET NULL, -- Link/Fork 核心
    is_archived BOOLEAN NOT NULL DEFAULT false,
    
    correct_answer JSONB NOT NULL DEFAULT '{}'::jsonb,
    correct_answer_text TEXT, -- Backup
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- [V5.9 Fork Sync] Version Control
    content_hash TEXT,           -- SHA256(title, content, type, choices, answer)
    last_synced_hash TEXT        -- Snapshot of parent's hash at last sync/fork
);

-- Indexing [Optimized]
CREATE INDEX IF NOT EXISTS idx_questions_user_id ON public.error_questions(user_id);
CREATE INDEX IF NOT EXISTS idx_questions_user_archived ON public.error_questions(user_id, is_archived); -- [Optimization] For main list filters
CREATE INDEX IF NOT EXISTS idx_questions_forked ON public.error_questions(forked_from); 
CREATE INDEX IF NOT EXISTS trgm_idx_questions_title ON public.error_questions USING GIN (title gin_trgm_ops); -- Requires: pg_trgm
-- CREATE INDEX IF NOT EXISTS idx_questions_hints ON public.error_questions USING GIN (hints); -- [P2-2 REMOVED] High write cost, low query value
CREATE UNIQUE INDEX IF NOT EXISTS uq_questions_user_forked_from ON public.error_questions(user_id, forked_from) WHERE forked_from IS NOT NULL;

CREATE TRIGGER trg_questions_updated BEFORE UPDATE ON public.error_questions FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
ALTER TABLE public.error_questions ENABLE ROW LEVEL SECURITY;

-- [V5.9] Content Hashing Trigger (Immutable Content Fingerprint)
-- 用于检测实质内容变更 (Diff Detection)
CREATE OR REPLACE FUNCTION public.calculate_question_content_hash()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  -- [P2-6] 扩展哈希覆盖范围：包含解释、难度、备选文本及资源链接
  -- 确保任何深度变更都能触发 Fork Sync 提醒
  NEW.content_hash := encode(extensions.digest(
    jsonb_build_array(
      NEW.title, 
      NEW.content, 
      NEW.question_type, 
      NEW.correct_answer,
      NEW.difficulty,
      NEW.explanation,
      NEW.correct_answer_text,
      NEW.image_url, 
      NEW.explanation_image_url,
      NEW.correct_answer_image_url,
      NEW.hints->'choices' -- Version controlled choices
    )::text,
    'sha256'
  ), 'hex');

  -- 如果是新 Fork (Insert) 且有来源，初始化同步状态
  IF TG_OP = 'INSERT' AND NEW.forked_from IS NOT NULL THEN
    -- 尝试获取父题当前的 hash (如果事务中父题可见)
    NEW.last_synced_hash := (SELECT content_hash FROM public.error_questions WHERE id = NEW.forked_from);
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER trg_questions_calc_hash
BEFORE INSERT OR UPDATE OF 
  title, content, question_type, correct_answer, difficulty, explanation,
  correct_answer_text, image_url, explanation_image_url, correct_answer_image_url, hints, forked_from
ON public.error_questions
FOR EACH ROW EXECUTE FUNCTION public.calculate_question_content_hash();

-- [Migration] 一次性补齐历史数据的 content_hash (针对旧版本平滑升级)
-- 确保 Parent 的 hash 存在，使 Fork Sync 机制能够正常初始化 last_synced_hash
UPDATE public.error_questions
SET content_hash = encode(extensions.digest(
  jsonb_build_array(
    title, content, question_type, correct_answer, difficulty, explanation,
    correct_answer_text, image_url, explanation_image_url, correct_answer_image_url,
    hints->'choices'
  )::text, 'sha256'
),'hex')
WHERE content_hash IS NULL;

-- [P1-FIX] correct_answer 结构校验触发器
-- 确保 correct_answer 对于有答案的题型包含必要字段
CREATE OR REPLACE FUNCTION public.validate_correct_answer()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  -- 允许空对象用于草稿，但非空时必须符合结构标准
  IF NEW.correct_answer = '{}'::jsonb THEN
    RETURN NEW;
  END IF;

  -- 校验 type 字段（必须存在）
  IF NOT (NEW.correct_answer ? 'type') THEN
    RAISE EXCEPTION 'correct_answer must contain a "type" field';
  END IF;

  -- [P2-FIX] 校验 correct_answer.type 与 question_type 的强一致性
  IF (NEW.correct_answer->>'type') IS DISTINCT FROM (NEW.question_type::text) THEN
    RAISE EXCEPTION 'correct_answer.type ("%") must match question_type ("%")', NEW.correct_answer->>'type', NEW.question_type;
  END IF;

  -- choice 校验
  IF NEW.question_type = 'choice' THEN
    -- [P2-5] 增加非空与唯一性校验
    IF NOT (
       (NEW.correct_answer ? 'choice_ids' AND jsonb_typeof(NEW.correct_answer->'choice_ids') = 'array' AND jsonb_array_length(NEW.correct_answer->'choice_ids') > 0) 
       OR NEW.correct_answer ? 'choice_id'
    ) THEN
      RAISE EXCEPTION 'Choice answer requires non-empty choice_ids (array) or choice_id';
    END IF;
    
    -- [P1-1] 增加选择项 ID 唯一性强校验
    IF NEW.correct_answer ? 'choice_ids' THEN
      IF jsonb_array_length(NEW.correct_answer->'choice_ids') <>
         (SELECT count(DISTINCT x) FROM jsonb_array_elements_text(NEW.correct_answer->'choice_ids') x) THEN
        RAISE EXCEPTION 'choice_ids must be unique';
      END IF;
    END IF;
  END IF;
  
  -- fill_blank 校验
  IF NEW.question_type = 'fill_blank' THEN
    IF NOT (NEW.correct_answer ? 'blanks' AND jsonb_typeof(NEW.correct_answer->'blanks') = 'array' AND jsonb_array_length(NEW.correct_answer->'blanks') > 0) THEN
      RAISE EXCEPTION 'Fill-blank answer requires non-empty blanks (array)';
    END IF;
  END IF;
  
  -- short_answer 校验
  IF NEW.question_type = 'short_answer' THEN
    IF NOT (NEW.correct_answer ? 'answers' AND jsonb_typeof(NEW.correct_answer->'answers') = 'array' AND jsonb_array_length(NEW.correct_answer->'answers') > 0) THEN
        RAISE EXCEPTION 'Short-answer requires non-empty answers (array)';
    END IF;
    
    -- [P1-1] 增加答案类型与非重复校验
    IF EXISTS (SELECT 1 FROM jsonb_array_elements(NEW.correct_answer->'answers') x WHERE jsonb_typeof(x) <> 'string') THEN
      RAISE EXCEPTION 'Short-answer entries must be strings';
    END IF;

    IF jsonb_array_length(NEW.correct_answer->'answers') <>
       (SELECT count(DISTINCT x) FROM jsonb_array_elements_text(NEW.correct_answer->'answers') x) THEN
      RAISE EXCEPTION 'Short-answer entries must be unique';
    END IF;
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER trg_validate_correct_answer
BEFORE INSERT OR UPDATE ON public.error_questions
FOR EACH ROW EXECUTE FUNCTION public.validate_correct_answer();

-- 2.3.1 题目关联标签 (Question Tags) - Assets Layer
-- 定位: 题目的"固有属性" (如知识点)。
-- 区别: 个性化标签 (如"我要复习") stored in cards.personal_tags (Overlay).
CREATE TABLE public.error_question_tags (
    question_id UUID NOT NULL REFERENCES public.error_questions(id) ON DELETE CASCADE,
    tag_id UUID NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), -- [V5.8 Traceability] 用于精准回滚 merge
    CONSTRAINT error_question_tags_pkey PRIMARY KEY (question_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_eq_tags_qid ON public.error_question_tags(question_id);
CREATE INDEX IF NOT EXISTS idx_eq_tags_tid ON public.error_question_tags(tag_id);
ALTER TABLE public.error_question_tags ENABLE ROW LEVEL SECURITY;

-- RLS: Follows Question Ownership
-- 1. Read: If I can see the question, I can see its tags (only if tag is NOT soft-deleted)
CREATE POLICY "qtags_read_shared" ON public.error_question_tags FOR SELECT TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.error_questions q WHERE q.id = question_id AND (q.user_id IS NULL OR q.user_id = (SELECT auth.uid())))
  AND EXISTS (SELECT 1 FROM public.tags t WHERE t.id = tag_id AND t.deleted_at IS NULL) -- [P2-7] Soft-delete Check
);

-- [P1-FIX] 2. Write: I can only tag MY questions with VISIBLE tags
-- 防止挂别人的私有 tag 到自己题目
CREATE POLICY "qtags_write_mine" ON public.error_question_tags FOR INSERT TO authenticated
WITH CHECK (
  -- Question must be mine
  EXISTS (SELECT 1 FROM public.error_questions q WHERE q.id = question_id AND q.user_id = (SELECT auth.uid()))
  -- Tag must be visible (public or mine) AND NOT soft-deleted
  AND EXISTS (SELECT 1 FROM public.tags t WHERE t.id = tag_id AND (t.user_id IS NULL OR t.user_id = (SELECT auth.uid())) AND t.deleted_at IS NULL)
);

CREATE POLICY "qtags_del_mine" ON public.error_question_tags FOR DELETE TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.error_questions q WHERE q.id = question_id AND q.user_id = (SELECT auth.uid()))
);

-- 2.4 FSRS 卡片 (Cards)
CREATE TABLE public.cards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- user_id is NOT NULL - Core security invariant
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- [P2-FIX] RESTRICT ensures questions cannot be deleted while referenced by cards
    question_id UUID NOT NULL REFERENCES public.error_questions(id) ON DELETE RESTRICT,
    
    -- FSRS State (Strictly typed)
    state SMALLINT NOT NULL DEFAULT 0 CHECK (state BETWEEN 0 AND 3),
    stability DOUBLE PRECISION NOT NULL DEFAULT 0.4,
    difficulty DOUBLE PRECISION NOT NULL DEFAULT 5 CHECK (difficulty BETWEEN 1 AND 10),
    lapses INTEGER NOT NULL DEFAULT 0,
    reps INTEGER NOT NULL DEFAULT 0,
    last_review TIMESTAMPTZ,
    due TIMESTAMPTZ NOT NULL DEFAULT now(),
    elapsed_days INTEGER NOT NULL DEFAULT 0,
    scheduled_days INTEGER NOT NULL DEFAULT 0,
    
    -- Overlay
    notes TEXT,
    last_wrong_answer TEXT,                 -- [P0-1 FIX] 从题目表移动到此
    last_user_answer JSONB DEFAULT '{}'::jsonb, -- 行为层：最近作答记录
    personal_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    subscribed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    -- Meta
    migrated_from_sm2 BOOLEAN NOT NULL DEFAULT false,
    sm2_migrated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    UNIQUE(user_id, question_id) 
);
CREATE INDEX IF NOT EXISTS idx_cards_user_due ON public.cards(user_id, due);
CREATE INDEX IF NOT EXISTS idx_cards_question ON public.cards(question_id); -- Optimize reverse lookup
CREATE TRIGGER trg_cards_updated BEFORE UPDATE ON public.cards FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;

-- 2.5 复习日志 (Review Logs)
CREATE TABLE public.review_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    card_id UUID REFERENCES public.cards(id) ON DELETE SET NULL, -- [P2-FIX] Allow history retention after card deletion
    
    -- question_id 用于历史记录保留 (card 删除后仍可追溯题目)
    question_id UUID REFERENCES public.error_questions(id) ON DELETE SET NULL, 
    
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 4),
    source TEXT DEFAULT 'review',
    
    state SMALLINT NOT NULL,
    stability DOUBLE PRECISION NOT NULL,
    difficulty DOUBLE PRECISION NOT NULL,
    elapsed_days INTEGER NOT NULL,
    last_elapsed_days INTEGER NOT NULL,
    scheduled_days INTEGER NOT NULL,
    
    review_duration_ms INTEGER,
    review TIMESTAMPTZ NOT NULL DEFAULT now(),
    post_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    
    -- [V5.2] 算法版本化字段 (Algorithm Versioning)
    -- 用于: A/B 测试, 回滚定位, 数据分析
    algo_version TEXT NOT NULL DEFAULT 'fsrs_v5',
    
    -- [V5.3] 权重引用 (Integer Ref vs Hash String)
    -- 仅占 4 bytes，支持 100% 还原当时权重
    config_id INTEGER REFERENCES public.fsrs_configs(id),
    
    -- [V5.2] 幂等性保护 (Idempotency Protection)
    -- 防止网络重试/用户连点导致的重复复习记录
    client_request_id UUID,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN public.review_logs.algo_version IS 'Algorithm version: fsrs_v5, fsrs_v4, sm2_compat, etc.';
COMMENT ON COLUMN public.review_logs.config_id IS 'Reference to specific FSRS weights used at time of review; enables perfect restoration';
COMMENT ON COLUMN public.review_logs.client_request_id IS 'Client-generated UUID for idempotency; prevents duplicate reviews from network retries';

CREATE INDEX IF NOT EXISTS idx_logs_user_date ON public.review_logs(user_id, review);
CREATE INDEX IF NOT EXISTS idx_logs_card_id ON public.review_logs(card_id);
CREATE INDEX IF NOT EXISTS idx_logs_algo_version ON public.review_logs(algo_version);
CREATE INDEX IF NOT EXISTS idx_logs_config_id ON public.review_logs(config_id); -- [V5.3] 支持按权重配置聚合分析

-- [V5.2] 幂等性约束：同一用户的同一 request_id 只能写入一次
CREATE UNIQUE INDEX IF NOT EXISTS uq_logs_client_request ON public.review_logs(user_id, client_request_id) 
  WHERE client_request_id IS NOT NULL;

ALTER TABLE public.review_logs ENABLE ROW LEVEL SECURITY;

-- [P0-FIX] review_logs 冗余字段强一致性触发器
-- 确保 user_id 和 question_id 与 card_id 的归属严格一致，防止前端传入脏数据
CREATE OR REPLACE FUNCTION public.sync_review_log_denorm()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE 
  v_card_user_id UUID; 
  v_card_question_id UUID;
BEGIN
  IF NEW.card_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT user_id, question_id INTO v_card_user_id, v_card_question_id
  FROM public.cards WHERE id = NEW.card_id;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Card with id % not found', NEW.card_id;
  END IF;

  -- 自动填充 & 强一致性校验
  NEW.user_id := COALESCE(NEW.user_id, v_card_user_id);
  NEW.question_id := COALESCE(NEW.question_id, v_card_question_id);

  IF NEW.user_id <> v_card_user_id THEN
    RAISE EXCEPTION 'User ID mismatch between log and card';
  END IF;
  
  IF NEW.question_id <> v_card_question_id THEN
    RAISE EXCEPTION 'Question ID mismatch between log and card';
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER trg_logs_sync_denorm
BEFORE INSERT ON public.review_logs
FOR EACH ROW EXECUTE FUNCTION public.sync_review_log_denorm();

-- 2.6 考试记录 (Exam Records)
CREATE TABLE public.exam_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    subject_id UUID REFERENCES public.subjects(id),
    title TEXT NOT NULL,
    mode public.exam_mode_enum NOT NULL DEFAULT 'practice'::public.exam_mode_enum,
    question_count INTEGER NOT NULL,
    config JSONB DEFAULT '{}'::jsonb,
    answers JSONB DEFAULT '{}'::jsonb,
    results JSONB DEFAULT '{}'::jsonb,
    question_ids UUID[] NOT NULL DEFAULT '{}',
    duration_seconds INTEGER DEFAULT 0,
    score DOUBLE PRECISION DEFAULT 0,
    status public.exam_status_enum NOT NULL DEFAULT 'in_progress'::public.exam_status_enum,
    start_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time TIMESTAMPTZ,
    template_id TEXT,
    answer_mode public.answer_mode_enum DEFAULT 'online'::public.answer_mode_enum,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- [Robustness] 确保数组长度必须等于声明的题目数
    CONSTRAINT exam_records_count_match CHECK (cardinality(question_ids) = question_count)
);

-- [V5.2] 2.8 导入任务表 (Import Jobs) - Job Queue Pattern
-- 支持: 可重试, 断点续传, 错误追踪
CREATE TABLE public.import_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- 文件信息
    file_path TEXT NOT NULL,  -- Storage path: 'imports/{user_id}/{filename}'
    file_name TEXT NOT NULL,
    file_size_bytes BIGINT,
    file_type public.import_file_type_enum NOT NULL,
    
    -- 状态机
    status public.job_status_enum NOT NULL DEFAULT 'queued'::public.job_status_enum,
    
    -- 进度追踪
    total_rows INTEGER,
    processed_rows INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    error_count INTEGER DEFAULT 0,
    
    -- 错误详情
    last_error TEXT,
    error_details JSONB DEFAULT '[]'::jsonb,  -- [{row: 5, error: "..."}]
    
    -- 断点续传
    checkpoint_row INTEGER DEFAULT 0,
    
    -- [V5.2] Worker 抢占/重试字段 (P2 增强)
    attempts INTEGER NOT NULL DEFAULT 0,           -- 重试次数
    max_attempts INTEGER NOT NULL DEFAULT 3,       -- 最大重试次数
    locked_at TIMESTAMPTZ,                         -- Worker 锁定时间
    locked_by TEXT,                                -- Worker 标识 (hostname/pod-id)
    next_retry_at TIMESTAMPTZ,                     -- 下次重试时间
    
    -- 配置
    config JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {subject_id, tags, etc.}
    
    -- 时间戳
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_exam_updated BEFORE UPDATE ON public.exam_records FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- [Documentation] JSON structure definitions as comments
COMMENT ON COLUMN public.exam_records.config IS 'Structure: { "filters": { "tagIds": [], "priority": "weakness" }, "settings": { "timeLimit": 60 } }';
COMMENT ON COLUMN public.exam_records.answers IS 'Format: { "question_id": { "choice": "A", "blanks": [], "text": "", "imageUrls": [] } }';
COMMENT ON COLUMN public.exam_records.results IS 'Format: { "question_id": { "score": 0, "isCorrect": false, "aiReason": "" } }';
COMMENT ON COLUMN public.error_questions.hints IS 'Structure: { "choices": [{ "id": "uuid", "text": "" }], "optionAnalysis": { "uuid": { "why": "" } }, "hints": [] }';
-- [Optimization] GIN Index for "Which exams contain this question?"
CREATE INDEX IF NOT EXISTS idx_exam_records_question_ids_completed
ON public.exam_records USING GIN (question_ids)
WHERE status = 'completed';
ALTER TABLE public.exam_records ENABLE ROW LEVEL SECURITY;

-- 2.7 复习设置 (Settings)
CREATE TABLE public.review_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    request_retention DOUBLE PRECISION DEFAULT 0.9,
    maximum_interval INTEGER DEFAULT 365,
    enable_fuzz BOOLEAN DEFAULT true,
    
    -- Timezone & Scheduler
    timezone TEXT NOT NULL DEFAULT 'UTC', -- e.g. 'Asia/Shanghai'
    rollover_hour SMALLINT NOT NULL DEFAULT 4 CHECK (rollover_hour BETWEEN 0 AND 23), -- 4 AM split
    
    weights JSONB DEFAULT '[0.212,1.2931,2.3065,8.2956,6.4133,0.8334,3.0194,0.001,1.8722,0.1666,0.796,1.4835,0.0614,0.2629,1.6483,0.6014,1.8729,0.5425,0.0912,0.0658,0.1542]'::jsonb,
    time_estimation JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    -- [P1-FIX] FSRS 权重长度校验
    CONSTRAINT review_settings_weights_check CHECK (
        jsonb_typeof(weights) = 'array' AND jsonb_array_length(weights) = 21
    )
);

-- [P1-FIX] 全局默认行唯一 (Only one NULL user_id row)
CREATE UNIQUE INDEX IF NOT EXISTS uq_settings_global_null ON public.review_settings ( (user_id IS NULL) ) WHERE user_id IS NULL;

CREATE TRIGGER trg_settings_updated BEFORE UPDATE ON public.review_settings FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
ALTER TABLE public.review_settings ENABLE ROW LEVEL SECURITY;

-- [V5.6] 管理操作日志 (Management Logs) - 支持回滚
CREATE TABLE public.management_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    op_type public.mgmt_op_type_enum NOT NULL,
    entity_type public.mgmt_entity_type_enum NOT NULL,
    source_id UUID NOT NULL,
    target_id UUID,                     -- NULL for delete
    affected_ids UUID[] NOT NULL DEFAULT '{}',    -- Questions or relations moved
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    undone_at TIMESTAMPTZ,              -- [V5.8 Audit] 是否已注销
    undone_by UUID REFERENCES auth.users(id),
    undo_metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_mgt_logs_user ON public.management_logs(user_id);
ALTER TABLE public.management_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "mgt_logs_isolation" ON public.management_logs FOR SELECT TO authenticated USING (user_id = (SELECT auth.uid()));

-- ============================================
-- 3. RLS 安全策略 (Strict & Complete)
-- ============================================

-- 3.1 Public Assets (Subjects/Tags)
-- [V5.8 Logic] RLS 必须过滤已软删除行
CREATE POLICY "subjects_read_all" ON public.subjects FOR SELECT TO authenticated 
USING ((user_id IS NULL OR user_id = (SELECT auth.uid())) AND deleted_at IS NULL);

-- [P0-2 FIX] 拆分策略以支持软删除 (deleted_at 更新)
CREATE POLICY "subjects_insert_mine" ON public.subjects FOR INSERT TO authenticated 
WITH CHECK (user_id = (SELECT auth.uid()) AND deleted_at IS NULL);

CREATE POLICY "subjects_update_mine" ON public.subjects FOR UPDATE TO authenticated 
USING (user_id = (SELECT auth.uid()))
WITH CHECK (user_id = (SELECT auth.uid())); -- 允许将 deleted_at 设为非空

CREATE POLICY "tags_read_all" ON public.tags FOR SELECT TO authenticated 
USING ((user_id IS NULL OR user_id = (SELECT auth.uid())) AND deleted_at IS NULL);

CREATE POLICY "tags_insert_mine" ON public.tags FOR INSERT TO authenticated 
WITH CHECK (user_id = (SELECT auth.uid()) AND deleted_at IS NULL);

CREATE POLICY "tags_update_mine" ON public.tags FOR UPDATE TO authenticated 
USING (user_id = (SELECT auth.uid()))
WITH CHECK (user_id = (SELECT auth.uid())); -- 允许将 deleted_at 设为非空

-- [P0-2 FIX] 禁止物理删除，强制走软删除逻辑
CREATE OR REPLACE FUNCTION public.prevent_hard_delete()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  -- [P2-9] 安全性增强：基于角色校验而非不安全的会话 GUC
  -- 仅允许 service_role 角色执行物理删除
  IF current_user = 'service_role' OR pg_has_role(current_user, 'service_role', 'member') THEN
    RETURN OLD;
  END IF;

  RAISE EXCEPTION 'Hard delete is not allowed for current role; use soft delete (set deleted_at)';
END $$;

CREATE TRIGGER trg_subjects_no_hard_delete BEFORE DELETE ON public.subjects FOR EACH ROW EXECUTE FUNCTION public.prevent_hard_delete();
CREATE TRIGGER trg_tags_no_hard_delete BEFORE DELETE ON public.tags FOR EACH ROW EXECUTE FUNCTION public.prevent_hard_delete();

-- 3.2 Error Questions (Read Shared / Write Private)
CREATE POLICY "questions_read_shared" ON public.error_questions FOR SELECT TO authenticated 
USING (user_id IS NULL OR user_id = (SELECT auth.uid()));

CREATE POLICY "questions_write_mine" ON public.error_questions FOR INSERT TO authenticated 
WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY "questions_mod_mine" ON public.error_questions FOR UPDATE TO authenticated 
USING (user_id = (SELECT auth.uid())) WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY "questions_del_mine" ON public.error_questions FOR DELETE TO authenticated 
USING (user_id = (SELECT auth.uid()));

-- 3.3 Cards (Strictly Private + Safe Linking)
CREATE POLICY "cards_read_mine" ON public.cards FOR SELECT TO authenticated 
USING (user_id = (SELECT auth.uid()));

-- INSERT: Must own the card and can see the question
CREATE POLICY "cards_insert_safe" ON public.cards FOR INSERT TO authenticated 
WITH CHECK (
  user_id = (SELECT auth.uid()) 
  AND EXISTS (
    SELECT 1 FROM public.error_questions q 
    WHERE q.id = question_id 
      AND (q.user_id IS NULL OR q.user_id = (SELECT auth.uid()))
  )
);

-- [P0-FIX] UPDATE: Must own the card AND new question_id must be visible
-- 防止通过 UPDATE 将卡片指向不可见的题目
CREATE POLICY "cards_mod_safe" ON public.cards FOR UPDATE TO authenticated 
USING (user_id = (SELECT auth.uid()))
WITH CHECK (
  user_id = (SELECT auth.uid())
  AND EXISTS (
    SELECT 1 FROM public.error_questions q 
    WHERE q.id = question_id 
      AND (q.user_id IS NULL OR q.user_id = (SELECT auth.uid()))
  )
);

CREATE POLICY "cards_del_mine" ON public.cards FOR DELETE TO authenticated 
USING (user_id = (SELECT auth.uid()));

-- 3.4 Review Logs (Strict Isolation)
-- [P0-FIX] 分离 INSERT 和 SELECT 策略，INSERT 必须校验 card_id 归属
CREATE POLICY "logs_read_mine" ON public.review_logs FOR SELECT TO authenticated 
USING (user_id = (SELECT auth.uid()));

CREATE POLICY "logs_insert_safe" ON public.review_logs FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM public.cards c WHERE c.id = card_id AND c.user_id = (SELECT auth.uid()))
);

-- UPDATE/DELETE 通常不需要（日志不可变），但保留基本隔离
CREATE POLICY "logs_del_mine" ON public.review_logs FOR DELETE TO authenticated 
USING (user_id = (SELECT auth.uid()));

-- 3.5 Exams/Settings (Private)
CREATE POLICY "exams_isolation" ON public.exam_records FOR ALL TO authenticated 
USING (user_id = (SELECT auth.uid())) WITH CHECK (user_id = (SELECT auth.uid()));

CREATE POLICY "settings_isolation" ON public.review_settings FOR ALL TO authenticated 
USING (user_id = (SELECT auth.uid())) WITH CHECK (user_id = (SELECT auth.uid()));

-- Settings READ allows viewing default (user_id IS NULL)
CREATE POLICY "settings_read_def" ON public.review_settings FOR SELECT TO authenticated 
USING (user_id IS NULL OR user_id = (SELECT auth.uid()));


-- ============================================
-- 4. 核心 RPC & 触发器 (Logic)
-- ============================================

-- [V5.8 Security Model]
-- 所有 SECURITY DEFINER 函数必须：
-- 1. 明确 SET search_path = pg_catalog, public (防止搜索路径劫持)
-- 2. 内部执行 auth.uid() 鉴权 (绕过 RLS)
-- 3. 仅限 authenticated 或 service_role 调用
-- 4. 推荐由 postgres 角色拥有
CREATE OR REPLACE FUNCTION public.fork_question_to_private(p_question_id UUID) 
RETURNS UUID 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_uid UUID := (SELECT auth.uid());
  v_new_q_id UUID;
  v_origin public.error_questions%ROWTYPE;
BEGIN
  -- [P0-FIX] 可见性检查: 只能 fork 公共题或自己的题
  SELECT * INTO v_origin 
  FROM public.error_questions 
  WHERE id = p_question_id 
    AND (user_id IS NULL OR user_id = v_uid)
    AND is_archived = false; -- [V5.5 Logic] 禁止 Fork 已归档题目
    
  IF v_origin.id IS NULL THEN 
    RAISE EXCEPTION 'Question not found, access denied, or archived'; 
  END IF;

  -- [V5.6 Consistency] 检查题目所属学科是否已被软删除
  IF v_origin.subject_id IS NOT NULL THEN
    IF EXISTS (SELECT 1 FROM public.subjects WHERE id = v_origin.subject_id AND deleted_at IS NOT NULL) THEN
      RAISE EXCEPTION 'Question belongs to a deleted subject and cannot be forked';
    END IF;
  END IF;

  -- [V5.5 Logic Close-loop] 禁止 Fork 已归档题目
  IF v_origin.is_archived THEN
    RAISE EXCEPTION 'Cannot fork an archived question';
  END IF;
  
  -- 如果已经是自己的题，不需要 fork
  IF v_origin.user_id = v_uid THEN
    RAISE EXCEPTION 'Cannot fork your own question';
  END IF;

  -- [P1-FIX] 幂等性检查：防止重复 fork (Optimization & Race Condition Handling)
  -- 1. Try to fetch existing (Idempotency)
  SELECT id INTO v_new_q_id FROM public.error_questions 
  WHERE user_id = v_uid AND forked_from = p_question_id;
  
  -- 2. If not found, try to insert (Safe Concurrency)
  IF v_new_q_id IS NULL THEN
    BEGIN
      INSERT INTO public.error_questions (
        user_id, title, content, question_type, difficulty,
        correct_answer, correct_answer_text, explanation,
        correct_answer_image_url, explanation_image_url, image_url,
        hints, metadata, subject_id, forked_from
      )
      VALUES (
        v_uid, v_origin.title, v_origin.content, v_origin.question_type, v_origin.difficulty,
        v_origin.correct_answer, v_origin.correct_answer_text, v_origin.explanation,
        v_origin.correct_answer_image_url, v_origin.explanation_image_url, v_origin.image_url,
        v_origin.hints, 
        COALESCE(v_origin.metadata, '{}'::jsonb) || jsonb_build_object('forked_at', now()::text),
        v_origin.subject_id, p_question_id
      )
      RETURNING id INTO v_new_q_id;
      
      -- Clone Tags (only if we created the question)
      INSERT INTO public.error_question_tags (question_id, tag_id)
      SELECT v_new_q_id, eqt.tag_id 
      FROM public.error_question_tags eqt
      JOIN public.tags t ON t.id = eqt.tag_id
      WHERE eqt.question_id = p_question_id
        AND (t.user_id IS NULL OR t.user_id = v_uid);
        
    EXCEPTION WHEN unique_violation THEN
      -- Race condition caught: fetch the one created by the other tx
      SELECT id INTO v_new_q_id FROM public.error_questions 
      WHERE user_id = v_uid AND forked_from = p_question_id;
    END;
  END IF;
  
  -- [P0-FIX] Card Logic Optimization (Robust Concurrency)
  -- 逻辑：确保用户拥有 v_new_q_id 的卡片，且不残留 p_question_id 的卡片
  
  -- A. 检查新卡是否存在 (可能是之前的 fork 或并发 tx 创建的)
  IF EXISTS (SELECT 1 FROM public.cards WHERE user_id = v_uid AND question_id = v_new_q_id) THEN
      -- 新卡已存在：只需清理旧卡 (如果存在)
      DELETE FROM public.cards WHERE user_id = v_uid AND question_id = p_question_id;
  ELSE
      -- 新卡不存在：尝试将旧卡迁移为新卡
      UPDATE public.cards 
      SET question_id = v_new_q_id, updated_at = NOW()
      WHERE user_id = v_uid AND question_id = p_question_id;
      
      -- 如果没有旧卡可迁移，则创建新卡
      IF NOT FOUND THEN
        INSERT INTO public.cards (user_id, question_id, state)
        VALUES (v_uid, v_new_q_id, 0) -- 0 = New
        ON CONFLICT (user_id, question_id) DO NOTHING; -- Final safety net
      END IF;
  END IF;
  
  RETURN v_new_q_id;
END $$;

REVOKE ALL ON FUNCTION public.fork_question_to_private(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.fork_question_to_private(UUID) TO authenticated;

-- [V5.2] Function: Atomic Review Storage (Pure Persistence Layer)
-- 职责分离：
--   - 算法计算：Elysia + Rust (fsrs-rs)
--   - 本函数只负责：锁 + 校验 + 原子写入
-- 保证:
--   1. FOR UPDATE 锁防止并发更新
--   2. 事务原子性：log + card 同时成功/失败
--   3. 幂等性：相同 client_request_id 返回缓存结果
-- [V5.4] Function: Atomic Review Storage (Pure Persistence Layer)
-- 职责分离：
--   - 算法计算：Elysia + Rust (fsrs-rs)
--   - 本函数只负责：锁 + 校验 + 原子写入
-- 保证:
--   1. FOR UPDATE 锁防止并发更新
--   2. 事务原子性：log + card 同时成功/失败
--   3. 幂等性：相同 client_request_id 返回完整 post_state 结果
CREATE OR REPLACE FUNCTION public.submit_review(
  -- 基础参数
  p_user_id UUID,                        -- [V5.4] 显式传入 UID，面向 service_role 
  p_card_id UUID,
  p_rating INTEGER,
  
  -- 算法计算结果 (由 Elysia/Rust 传入)
  p_new_state SMALLINT,
  p_new_stability DOUBLE PRECISION,
  p_new_difficulty DOUBLE PRECISION,
  p_new_due TIMESTAMPTZ,
  p_scheduled_days INTEGER,
  
  -- 元数据与权重
  p_duration_ms INTEGER DEFAULT NULL,
  p_algo_version TEXT DEFAULT 'fsrs_v5',
  p_weights JSONB DEFAULT NULL,          -- [V5.3] 传入原始权重，DB 自动去重归档
  p_client_request_id UUID DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = pg_catalog, public
AS $$
DECLARE 
  v_card public.cards%ROWTYPE;
  v_now TIMESTAMPTZ := now();
  v_elapsed_days INTEGER;
  v_existing_log public.review_logs%ROWTYPE;
  v_weights_hash TEXT;
  v_config_id INTEGER;
  v_post_state JSONB;
BEGIN
  -- =========================================
  -- 0. 鲁棒性校验 (V5.5)
  -- =========================================
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'p_user_id is required for service_role calls';
  END IF;

  -- =========================================
  -- 1. 参数校验
  -- =========================================
  IF p_rating NOT BETWEEN 1 AND 4 THEN
    RAISE EXCEPTION 'Rating must be between 1 and 4';
  END IF;
  
  IF p_new_state NOT BETWEEN 0 AND 3 THEN
    RAISE EXCEPTION 'State must be between 0 and 3';
  END IF;
  
  IF p_new_difficulty NOT BETWEEN 1 AND 10 THEN
    RAISE EXCEPTION 'Difficulty must be between 1 and 10';
  END IF;
  
  IF p_new_stability < 0 THEN
    RAISE EXCEPTION 'Stability must be non-negative';
  END IF;

  -- [V5.4] 权重结构校验补齐
  IF p_weights IS NOT NULL AND (jsonb_typeof(p_weights) <> 'array' OR jsonb_array_length(p_weights) <> 21) THEN
    RAISE EXCEPTION 'FSRS weights must be an array of length 21';
  END IF;

  -- =========================================
  -- 2. 幂等性检查
  -- =========================================
  IF p_client_request_id IS NOT NULL THEN
    SELECT * INTO v_existing_log 
    FROM public.review_logs 
    WHERE user_id = p_user_id AND client_request_id = p_client_request_id;
    
    IF FOUND THEN
      -- [V5.4] 返回之前保存的完整 post_state，确保响应一致性
      RETURN v_existing_log.post_state || jsonb_build_object(
        'success', true,
        'idempotent', true,
        'message', 'Duplicate request, returning cached result'
      );
    END IF;
  END IF;

  -- =========================================
  -- 3. 权重归档 (Content-Addressable)
  -- =========================================
  IF p_weights IS NOT NULL THEN
    -- [P1-1] 改用 sha256
    v_weights_hash := encode(extensions.digest(p_weights::text, 'sha256'), 'hex');
    
    -- 原子性查找或插入归档记录
    WITH ins AS (
      INSERT INTO public.fsrs_configs (hash, weights)
      VALUES (v_weights_hash, p_weights)
      ON CONFLICT (hash) DO NOTHING
      RETURNING id
    )
    SELECT id INTO v_config_id FROM ins
    UNION ALL
    SELECT id FROM public.fsrs_configs WHERE hash = v_weights_hash
    LIMIT 1;
  END IF;

  -- =========================================
  -- 4. 锁定卡片行
  -- =========================================
  SELECT * INTO v_card 
  FROM public.cards 
  WHERE id = p_card_id AND user_id = p_user_id
  FOR UPDATE;
  
  IF NOT FOUND THEN 
    RAISE EXCEPTION 'Card not found or access denied'; 
  END IF;

  v_elapsed_days := GREATEST(0, 
    EXTRACT(DAY FROM (v_now - COALESCE(v_card.last_review, v_card.created_at)))::INTEGER
  );

  -- 构造 post_state（用于幂等返回及分析）
  v_post_state := jsonb_build_object(
    'card_id', p_card_id,
    'new_state', p_new_state,
    'new_due', p_new_due,
    'scheduled_days', p_scheduled_days,
    'config_id', v_config_id,
    'algo_version', p_algo_version
  );

  -- =========================================
  -- 5. 写入复习日志
  -- =========================================
  INSERT INTO public.review_logs (
    card_id, rating, source,
    state, stability, difficulty,
    elapsed_days, last_elapsed_days, scheduled_days,
    review_duration_ms, review, algo_version, config_id,
    client_request_id, post_state
  ) VALUES (
    p_card_id, p_rating, 'review',
    v_card.state,
    v_card.stability,
    v_card.difficulty,
    v_elapsed_days, v_card.elapsed_days, p_scheduled_days,
    p_duration_ms, v_now, p_algo_version, v_config_id,
    p_client_request_id, v_post_state
  );

  -- =========================================
  -- 6. 更新卡片状态
  -- =========================================
  UPDATE public.cards SET
    state = p_new_state,
    stability = p_new_stability,
    difficulty = p_new_difficulty,
    due = p_new_due,
    last_review = v_now,
    elapsed_days = v_elapsed_days,
    scheduled_days = p_scheduled_days,
    reps = reps + 1,
    lapses = CASE WHEN p_rating = 1 THEN lapses + 1 ELSE lapses END,
    updated_at = v_now
  WHERE id = p_card_id;

  RETURN v_post_state || jsonb_build_object('success', true, 'idempotent', false);
END $$;

-- [V5.8 Security Model]
-- 职责分离：算法计算 (Elysia) vs. 原子持久化 (DB)
-- 保证 FOR UPDATE 串行化与幂等性防护
REVOKE ALL ON FUNCTION public.submit_review(UUID, UUID, INTEGER, SMALLINT, DOUBLE PRECISION, DOUBLE PRECISION, TIMESTAMPTZ, INTEGER, INTEGER, TEXT, JSONB, UUID) FROM PUBLIC, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_review(UUID, UUID, INTEGER, SMALLINT, DOUBLE PRECISION, DOUBLE PRECISION, TIMESTAMPTZ, INTEGER, INTEGER, TEXT, JSONB, UUID) TO service_role;

-- [V5.2] Function: Claim Import Job (Worker Contention Safe)
-- Worker 使用 FOR UPDATE SKIP LOCKED 原子抢占任务
-- 返回: 抢到的任务详情，或 NULL（无可用任务）
CREATE OR REPLACE FUNCTION public.claim_import_job(
  p_worker_id TEXT,                     -- Worker 标识 (hostname/pod-id)
  p_lock_duration_minutes INTEGER DEFAULT 10
) RETURNS JSONB
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = pg_catalog, public
AS $$
DECLARE 
  v_job public.import_jobs%ROWTYPE;
  v_now TIMESTAMPTZ := now();
BEGIN
  -- 原子抢占：SELECT FOR UPDATE SKIP LOCKED
  -- [P2-4 Logic Fix] 包含 'partial' 状态，支持断点续传
  -- [P1-3 Patch] 增加重试门禁校验
  SELECT * INTO v_job
  FROM public.import_jobs
  WHERE (
    status = 'queued' 
    OR (status = 'partial' AND (next_retry_at IS NULL OR next_retry_at <= v_now))
    OR (status = 'failed' AND attempts < max_attempts AND (next_retry_at IS NULL OR next_retry_at <= v_now))
    -- [V5.5 Robustness] 处理 locked_at 可能为 NULL 的边界情况
    OR (status = 'running' AND (locked_at IS NULL OR locked_at < v_now - (p_lock_duration_minutes || ' minutes')::INTERVAL)) 
  )
  ORDER BY created_at ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED;
  
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  
  -- 更新任务状态为 running 并锁定
  UPDATE public.import_jobs SET
    status = 'running',
    locked_at = v_now,
    locked_by = p_worker_id,
    attempts = attempts + 1,
    started_at = COALESCE(started_at, v_now),
    updated_at = v_now
  WHERE id = v_job.id;
  
  -- 返回任务详情
  RETURN jsonb_build_object(
    'job_id', v_job.id,
    'user_id', v_job.user_id,
    'file_path', v_job.file_path,
    'file_name', v_job.file_name,
    'file_type', v_job.file_type,
    'checkpoint_row', v_job.checkpoint_row,
    'config', v_job.config,
    'attempt', v_job.attempts + 1
  );
END $$;

-- [V5.8 Security Model]
-- Worker 使用 FOR UPDATE SKIP LOCKED 原子抢占任务
-- SECURITY DEFINER 确保 Worker 能够跨 RLS 权限处理队列
REVOKE ALL ON FUNCTION public.claim_import_job(TEXT, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_import_job(TEXT, INTEGER) TO service_role;  -- 只允许 service_role 调用


-- [V5.3] Function: Generate Exam Questions (Security & Consistency)
-- 职责: 1. 过滤已归档题目 2. RLS 隔离 3. 随机抽取
-- 确保考试中绝不会出现 is_archived = true 的题目
CREATE OR REPLACE FUNCTION public.get_exam_questions(
  p_subject_id UUID DEFAULT NULL,
  p_tag_ids UUID[] DEFAULT NULL,
  p_count INTEGER DEFAULT 20
) RETURNS SETOF UUID
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = pg_catalog, public
AS $$
BEGIN
  RETURN QUERY
  SELECT q.id
  FROM public.error_questions q
  LEFT JOIN public.error_question_tags eqt ON q.id = eqt.question_id
  WHERE (q.user_id = (SELECT auth.uid()) OR q.user_id IS NULL)
    AND (p_subject_id IS NULL OR q.subject_id = p_subject_id)
    AND (p_tag_ids IS NULL OR eqt.tag_id = ANY(p_tag_ids))
    AND q.is_archived = false  -- [P2-Logic FIX] 强校验归档状态
  GROUP BY q.id
  ORDER BY random() -- [P1-2 NOTE] 大数据量下可改用 TABLESAMPLE 或基于 Hash 的随机采样优化性能
  LIMIT p_count;
END $$;

-- [V5.8 Security Model]
-- 职责: 1. 过滤已归档题目 2. RLS 隔离 3. 随机抽取
-- SECURITY DEFINER 内部执行鉴权以配合 RLS
REVOKE ALL ON FUNCTION public.get_exam_questions(UUID, UUID[], INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_exam_questions(UUID, UUID[], INTEGER) TO authenticated;

-- ============================================
-- [V5.6] Advanced Entity Management RPCs (Merge/Undo)
-- ============================================

-- 1. Merge Subjects
CREATE OR REPLACE FUNCTION public.merge_subjects(p_source_id UUID, p_target_id UUID)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_uid UUID := (SELECT auth.uid());
  v_affected_ids UUID[];
  v_affected_exam_ids UUID[]; -- [P1-4 FIX] 补充声明变量
  v_log_id UUID;
BEGIN
  -- [V5.8 Protection] 源/目标相同保护
  IF p_source_id = p_target_id THEN
    RAISE EXCEPTION 'Source and target subject must be different';
  END IF;

  -- [V5.8 Concurrency] 事务级咨询锁
  PERFORM pg_advisory_xact_lock(hashtext('merge_subjects' || v_uid::text));

  -- 1. 权限与状态校验
  IF NOT EXISTS (SELECT 1 FROM public.subjects WHERE id = p_source_id AND user_id = v_uid AND deleted_at IS NULL) OR
     NOT EXISTS (SELECT 1 FROM public.subjects WHERE id = p_target_id AND user_id = v_uid AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'Source or target subject not found or access denied';
  END IF;

  -- [P1-4] 收集受影响的题目与考试记录 (用于精准回滚)
  SELECT array_agg(id) INTO v_affected_ids FROM public.error_questions WHERE subject_id = p_source_id AND user_id = v_uid;
  SELECT array_agg(id) INTO v_affected_exam_ids FROM public.exam_records WHERE subject_id = p_source_id AND user_id = v_uid;

  -- 3. 执行迁移
  UPDATE public.error_questions SET subject_id = p_target_id WHERE subject_id = p_source_id AND user_id = v_uid;
  UPDATE public.exam_records SET subject_id = p_target_id WHERE subject_id = p_source_id AND user_id = v_uid;

  -- 4. 软删除源学科
  UPDATE public.subjects SET deleted_at = now() WHERE id = p_source_id;

  -- 5. 记录日志 (全量快照以支持物理清理后的极致审计)
  INSERT INTO public.management_logs (user_id, op_type, entity_type, source_id, target_id, affected_ids, metadata)
  SELECT 
    v_uid, 'merge', 'subject', p_source_id, p_target_id, 
    COALESCE(v_affected_ids, '{}'), 
    jsonb_build_object(
      'exam_record_ids', COALESCE(v_affected_exam_ids, '{}'),
      'full_snapshot', (SELECT to_jsonb(s.*) FROM public.subjects s WHERE s.id = p_source_id),
      'source_name', (SELECT name FROM public.subjects WHERE id = p_source_id),
      'target_name', (SELECT name FROM public.subjects WHERE id = p_target_id)
    )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END $$;

-- 2. Merge Tags
CREATE OR REPLACE FUNCTION public.merge_tags(p_source_id UUID, p_target_id UUID)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_uid UUID := (SELECT auth.uid());
  v_affected_ids UUID[];
  v_affected_card_ids UUID[]; -- [V5.8] 追踪 JSONB 标签受影响的卡片
  v_log_id UUID;
  v_now_ts TIMESTAMPTZ := now();
BEGIN
  -- [V5.8 Protection]
  IF p_source_id = p_target_id THEN
    RAISE EXCEPTION 'Source and target tag must be different';
  END IF;

  -- [V5.8 Concurrency]
  PERFORM pg_advisory_xact_lock(hashtext('merge_tags' || v_uid::text));

  IF NOT EXISTS (SELECT 1 FROM public.tags WHERE id = p_source_id AND user_id = v_uid AND deleted_at IS NULL) OR
     NOT EXISTS (SELECT 1 FROM public.tags WHERE id = p_target_id AND user_id = v_uid AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'Source or target tag not found or access denied';
  END IF;

  -- 收集受影响题目（仅那些目前还没被打上 target_id 标签的题目）
  SELECT array_agg(question_id) INTO v_affected_ids 
  FROM public.error_question_tags 
  WHERE tag_id = p_source_id 
    AND question_id NOT IN (SELECT question_id FROM public.error_question_tags WHERE tag_id = p_target_id);

  -- 执行合并逻辑
  -- 1. 将源标签对应的题目，且目标标签未覆盖的，插入目标标签
  -- [V5.8 Note] 依赖 v_now_ts 的高精度与 pg_advisory_xact_lock 的串行化保证
  INSERT INTO public.error_question_tags (question_id, tag_id, created_at)
  SELECT question_id, p_target_id, v_now_ts FROM public.error_question_tags WHERE tag_id = p_source_id
  ON CONFLICT (question_id, tag_id) DO NOTHING;
  
  -- 2. 删除源标签的关联
  DELETE FROM public.error_question_tags WHERE tag_id = p_source_id;

  -- [V5.8 Deep Merge] 同步更新 cards 表中的个人标签 JSONB 数组 (Overlay Layer)
  -- 逻辑：替换数组中的 UUID 并去重
  WITH updated_cards AS (
    UPDATE public.cards SET 
      personal_tags = (
        SELECT jsonb_agg(DISTINCT val)
        FROM (
          SELECT CASE WHEN (v #>> '{}') = p_source_id::text THEN to_jsonb(p_target_id::text) ELSE v END AS val
          FROM jsonb_array_elements(personal_tags) AS v
        ) s
      ),
      updated_at = v_now_ts
    WHERE personal_tags ? p_source_id::text AND user_id = v_uid
    RETURNING id
  )
  SELECT array_agg(id) INTO v_affected_card_ids FROM updated_cards;

  -- 3. 软删除源标签
  UPDATE public.tags SET deleted_at = v_now_ts WHERE id = p_source_id;

  -- 记录日志 (全量快照以支持物理清理后的极致审计)
  INSERT INTO public.management_logs (user_id, op_type, entity_type, source_id, target_id, affected_ids, metadata)
  SELECT 
    v_uid, 'merge', 'tag', p_source_id, p_target_id, 
    COALESCE(v_affected_ids, '{}'), 
    jsonb_build_object(
      'merge_timestamp', v_now_ts,
      'affected_card_ids', COALESCE(v_affected_card_ids, '{}'),
      'full_snapshot', (SELECT to_jsonb(t.*) FROM public.tags t WHERE t.id = p_source_id),
      'source_name', (SELECT name FROM public.tags WHERE id = p_source_id),
      'target_name', (SELECT name FROM public.tags WHERE id = p_target_id)
    )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END $$;

-- 3. Undo Management Operation
CREATE OR REPLACE FUNCTION public.undo_management_op(p_log_id UUID)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_uid UUID := (SELECT auth.uid());
  v_log public.management_logs%ROWTYPE;
BEGIN
  -- [V5.8 Concurrency]
  PERFORM pg_advisory_xact_lock(hashtext('undo_management_op' || v_uid::text));

  SELECT * INTO v_log FROM public.management_logs WHERE id = p_log_id AND user_id = v_uid AND undone_at IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'Operation log not found or already undone'; END IF;

  -- 恢复实体
  IF v_log.entity_type = 'subject' THEN
    IF NOT EXISTS (SELECT 1 FROM public.subjects WHERE id = v_log.source_id) THEN
      RAISE EXCEPTION 'Cannot undo: Source subject (%) has been physically purged', v_log.source_id;
    END IF;
    UPDATE public.subjects SET deleted_at = NULL WHERE id = v_log.source_id;
    IF v_log.op_type = 'merge' THEN
      -- 还原题目学科归属
      UPDATE public.error_questions SET subject_id = v_log.source_id WHERE id = ANY(v_log.affected_ids);
      -- [P1-4] 还原考试记录 (基于 metadata 中的 precise ids)
      UPDATE public.exam_records SET subject_id = v_log.source_id 
      WHERE id = ANY(ARRAY(SELECT jsonb_array_elements_text(v_log.metadata->'exam_record_ids'))::UUID[]);
    END IF;
  ELSIF v_log.entity_type = 'tag' THEN
    IF NOT EXISTS (SELECT 1 FROM public.tags WHERE id = v_log.source_id) THEN
      RAISE EXCEPTION 'Cannot undo: Source tag (%) has been physically purged', v_log.source_id;
    END IF;
    UPDATE public.tags SET deleted_at = NULL WHERE id = v_log.source_id;
    IF v_log.op_type = 'merge' THEN
      -- [P1-5] 还原关系：重新建立与 source_id 的关联 (增加存在性校验防止 FK 失败)
      INSERT INTO public.error_question_tags (question_id, tag_id)
      SELECT qid, v_log.source_id
      FROM unnest(v_log.affected_ids) AS qid
      WHERE EXISTS (SELECT 1 FROM public.error_questions q WHERE q.id = qid);
      
      -- 2. 清理合并产生的多余关联：仅删除在 merge 发生瞬间创建的 target_id 关联
      -- [V5.8 Performance] 结合 created_at 与 affected_ids 提供精准识别，无需额外 source_log_id 列
      DELETE FROM public.error_question_tags 
      WHERE tag_id = v_log.target_id 
        AND question_id = ANY(v_log.affected_ids)
        AND created_at = (v_log.metadata->>'merge_timestamp')::TIMESTAMPTZ;

      -- 3. [V5.8 Deep Undo] 还原 cards 表中的个人标签
      IF v_log.metadata ? 'affected_card_ids' THEN
        UPDATE public.cards SET 
          personal_tags = (
            SELECT jsonb_agg(DISTINCT val)
            FROM (
              SELECT CASE WHEN (v #>> '{}') = v_log.target_id::text THEN v_log.source_id::text::jsonb ELSE v END AS val
              FROM jsonb_array_elements(personal_tags) AS v
            ) s
          )
        WHERE id = ANY(ARRAY(SELECT jsonb_array_elements_text(v_log.metadata->'affected_card_ids'))::UUID[]);
      END IF;
    END IF;
  END IF;

  -- [V5.8 Audit] 任务完成，标记已撤销，不再物理删除
  UPDATE public.management_logs SET 
    undone_at = now(),
    undone_by = v_uid,
    undo_metadata = jsonb_build_object('performed_at', now())
  WHERE id = p_log_id;

  RETURN TRUE;
END $$;

-- [V5.8 Security Model]
-- 管理类函数统一使用 SECURITY DEFINER 并内置 auth.uid() 校验
REVOKE ALL ON FUNCTION public.merge_subjects(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.merge_tags(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.undo_management_op(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.merge_subjects(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.merge_tags(UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.undo_management_op(UUID) TO authenticated;



-- [V5.2] 2.8 导入任务表表 (REMOVED: Moved to top for dependency order)

-- 4. Purge Soft Deleted Data (Maintenance)
-- [V5.8] 周期性安全清理逻辑：
-- 1. 只有当没有题目/记录引用时才执行物理删除 (Dependency-Aware)
-- 2. 结合 RPC 中的名称快照，即使物理删除，审计日志仍可读
CREATE OR REPLACE FUNCTION public.purge_soft_deleted_data(p_days_threshold INTEGER DEFAULT 30)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_subject_count INTEGER := 0;
  v_tag_count INTEGER := 0;
  v_log_count INTEGER := 0;
  v_threshold TIMESTAMPTZ := now() - (p_days_threshold || ' days')::INTERVAL;
BEGIN
  -- 1. 清理学科 (安全物理删除)
  -- 条件：软删除超过阈值 + 无任何题目引用 + 无任何考试记录引用
  DELETE FROM public.subjects s
  WHERE s.deleted_at IS NOT NULL 
    AND s.deleted_at < v_threshold
    AND NOT EXISTS (SELECT 1 FROM public.error_questions q WHERE q.subject_id = s.id)
    AND NOT EXISTS (SELECT 1 FROM public.exam_records e WHERE e.subject_id = s.id);
  GET DIAGNOSTICS v_subject_count = ROW_COUNT;

  -- 2. 清理标签 (安全物理删除)
  -- 条件：软删除超过阈值 + 关联表无引用
  DELETE FROM public.tags t
  WHERE t.deleted_at IS NOT NULL 
    AND t.deleted_at < v_threshold
    AND NOT EXISTS (SELECT 1 FROM public.error_question_tags eqt WHERE eqt.tag_id = t.id);
  GET DIAGNOSTICS v_tag_count = ROW_COUNT;

  -- 3. 清理已撤销的审计日志 (物理删除)
  DELETE FROM public.management_logs WHERE undone_at IS NOT NULL AND undone_at < v_threshold;
  GET DIAGNOSTICS v_log_count = ROW_COUNT;

  RETURN jsonb_build_object(
    'subjects_purged', v_subject_count,
    'tags_purged', v_tag_count,
    'logs_purged', v_log_count,
    'threshold_used', v_threshold,
    'status', 'safety_checks_performed'
  );
END $$;

-- [V5.8 Security Model]
-- 维护函数仅限 service_role (DBA/Cron) 调用，内置 search_path 保护
REVOKE ALL ON FUNCTION public.purge_soft_deleted_data(INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.purge_soft_deleted_data(INTEGER) TO service_role; -- 仅限后台任务/管理员

CREATE INDEX IF NOT EXISTS idx_import_jobs_user_status ON public.import_jobs(user_id, status);
-- [V5.8 Performance] 针对 Failed/Queued 的拉取索引
CREATE INDEX IF NOT EXISTS idx_import_jobs_pending ON public.import_jobs(status, next_retry_at) 
  WHERE status IN ('queued', 'failed');
-- [V5.8 Performance] 针对 Running 僵尸回收的专项索引 (locked_at 优先)
CREATE INDEX IF NOT EXISTS idx_import_jobs_running_locked
  ON public.import_jobs (locked_at, created_at)
  WHERE status = 'running';
CREATE TRIGGER trg_import_jobs_updated BEFORE UPDATE ON public.import_jobs FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
ALTER TABLE public.import_jobs ENABLE ROW LEVEL SECURITY;

-- RLS: 导入任务私有
CREATE POLICY "import_jobs_isolation" ON public.import_jobs FOR ALL TO authenticated 
USING (user_id = (SELECT auth.uid())) WITH CHECK (user_id = (SELECT auth.uid()));

COMMENT ON TABLE public.import_jobs IS 'Job Queue for reliable file imports with retry and checkpoint support';
COMMENT ON COLUMN public.import_jobs.status IS 'State machine: queued -> running -> (partial|done|failed)';
COMMENT ON COLUMN public.import_jobs.checkpoint_row IS 'Last successfully processed row for resume after failure';

-- ============================================
-- 5. Helper Views (Optimization)
-- ============================================

-- Due Cards View (Simplifies Frontend Query & RPC)
CREATE OR REPLACE VIEW public.v_due_cards
WITH (security_invoker = true)
AS
SELECT 
  c.id AS card_id,
  c.user_id,
  c.question_id,
  c.state,
  c.stability,    -- [Enhancement] Added for frontend sorting
  c.difficulty AS card_difficulty, -- [Enhancement] FSRS difficulty
  c.due,
  c.reps,
  c.lapses,
  q.title,
  q.question_type,
  q.difficulty AS question_difficulty, -- Question's intrinsic difficulty
  s.name  AS subject_name,
  s.color AS subject_color
FROM public.cards c
JOIN public.error_questions q ON c.question_id = q.id
LEFT JOIN public.subjects s ON q.subject_id = s.id
WHERE
  c.user_id = (SELECT auth.uid()) -- Pushdown filter for perf
  AND c.due <= now()
  AND q.is_archived = false
  AND (s.id IS NULL OR s.deleted_at IS NULL); -- [V5.6 Logic] 过滤已软删除学科

-- ============================================
-- 6. 数据一致性约束 (Consistency)
-- ============================================

-- [Enhancement] 防止 cards.question_id 指向已归档的题目
-- 使用触发器而非 CHECK 约束，因为 is_archived 可能后续变化
CREATE OR REPLACE FUNCTION public.check_card_question_active()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.error_questions q 
    WHERE q.id = NEW.question_id AND q.is_archived = true
  ) THEN
    RAISE EXCEPTION 'Cannot create/update card for archived question';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_card_check_archived
BEFORE INSERT OR UPDATE OF question_id ON public.cards
FOR EACH ROW EXECUTE FUNCTION public.check_card_question_active();

-- [V5.8] 防止题目关联到已软删除的资产
CREATE OR REPLACE FUNCTION public.check_asset_soft_deleted()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  -- 检查学科
  IF NEW.subject_id IS NOT NULL THEN
    IF EXISTS (SELECT 1 FROM public.subjects WHERE id = NEW.subject_id AND deleted_at IS NOT NULL) THEN
      RAISE EXCEPTION 'Cannot reference a soft-deleted subject (ID: %)', NEW.subject_id;
    END IF;
  END IF;

  -- 检查标签 (针对 error_question_tags)
  IF TG_TABLE_NAME = 'error_question_tags' THEN
    IF EXISTS (SELECT 1 FROM public.tags WHERE id = NEW.tag_id AND deleted_at IS NOT NULL) THEN
      RAISE EXCEPTION 'Cannot reference a soft-deleted tag (ID: %)', NEW.tag_id;
    END IF;
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER trg_questions_asset_deleted
BEFORE INSERT OR UPDATE OF subject_id ON public.error_questions
FOR EACH ROW EXECUTE FUNCTION public.check_asset_soft_deleted();

CREATE TRIGGER trg_qtags_asset_deleted
BEFORE INSERT OR UPDATE OF tag_id ON public.error_question_tags
FOR EACH ROW EXECUTE FUNCTION public.check_asset_soft_deleted();

-- [P0-3 FIX] 数据完整性触发器 (Public Asset Protection & Cross-User Isolation)
CREATE OR REPLACE FUNCTION public.check_public_asset_integrity()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  -- 1. 公共题目完整性 (error_questions)
  -- 规则：公共题不能引用私有学科
  IF TG_TABLE_NAME = 'error_questions' THEN
    IF NEW.user_id IS NULL AND NEW.subject_id IS NOT NULL THEN
      IF EXISTS (SELECT 1 FROM public.subjects s WHERE s.id = NEW.subject_id AND s.user_id IS NOT NULL) THEN
        RAISE EXCEPTION 'Public question cannot reference a private subject';
      END IF;
    END IF;
    
    -- [P2-FIX] 公共题目结构完整性: 公共题不应标记为 Fork
    IF NEW.user_id IS NULL AND NEW.forked_from IS NOT NULL THEN
      RAISE EXCEPTION 'Public questions cannot be forks';
    END IF;
    
    -- [P1-FIX] 私有题目隔离性 (error_questions)
    -- 规则：我的题目不能挂别人的私有学科 (FK 泄露防护)
    IF NEW.user_id IS NOT NULL AND NEW.subject_id IS NOT NULL THEN
      IF NOT EXISTS (
        SELECT 1 FROM public.subjects s 
        WHERE s.id = NEW.subject_id AND (s.user_id IS NULL OR s.user_id = NEW.user_id)
      ) THEN
        RAISE EXCEPTION 'Question cannot reference a subject owned by another user';
      END IF;
    END IF;
  END IF;

  -- 2. 标签关联完整性 (error_question_tags)
  IF TG_TABLE_NAME = 'error_question_tags' THEN
    -- 需要检查对应的题目是否是公共题目
    IF EXISTS (
      SELECT 1 FROM public.error_questions q 
      WHERE q.id = NEW.question_id AND q.user_id IS NULL
    ) THEN
      -- 如果是公共题目，tag 必须是公共 tag
      IF EXISTS (SELECT 1 FROM public.tags t WHERE t.id = NEW.tag_id AND t.user_id IS NOT NULL) THEN
        RAISE EXCEPTION 'Public question cannot reference a private tag';
      END IF;
    END IF;
  END IF;

  -- 3. [P1-FIX] 考试记录隔离性 (exam_records)
  IF TG_TABLE_NAME = 'exam_records' THEN
    IF NEW.subject_id IS NOT NULL THEN
      IF NOT EXISTS (
        SELECT 1 FROM public.subjects s 
        WHERE s.id = NEW.subject_id AND (s.user_id IS NULL OR s.user_id = NEW.user_id)
      ) THEN
        RAISE EXCEPTION 'Exam record cannot reference a subject owned by another user';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_questions_public_integrity ON public.error_questions;
CREATE TRIGGER trg_questions_public_integrity
BEFORE INSERT OR UPDATE ON public.error_questions
FOR EACH ROW EXECUTE FUNCTION public.check_public_asset_integrity();

DROP TRIGGER IF EXISTS trg_qtags_public_integrity ON public.error_question_tags;
CREATE TRIGGER trg_qtags_public_integrity
BEFORE INSERT OR UPDATE ON public.error_question_tags
FOR EACH ROW EXECUTE FUNCTION public.check_public_asset_integrity();

DROP TRIGGER IF EXISTS trg_exams_isolation_integrity ON public.exam_records;
CREATE TRIGGER trg_exams_isolation_integrity
BEFORE INSERT OR UPDATE ON public.exam_records
FOR EACH ROW EXECUTE FUNCTION public.check_public_asset_integrity();

-- [P1-3 FIX] 考试题目可见性与归档状态强校验
CREATE OR REPLACE FUNCTION public.validate_exam_question_security()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  -- 检查数组中每一个题目 ID
  IF EXISTS (
    SELECT 1 
    FROM unnest(NEW.question_ids) AS qid
    LEFT JOIN public.error_questions q ON q.id = qid
    WHERE 
      q.id IS NULL -- 不存在
      OR q.is_archived = true -- 已归档
      -- 跨用户越权 (除非是公共题目)
      OR (q.user_id IS NOT NULL AND q.user_id <> NEW.user_id)
  ) THEN
    RAISE EXCEPTION 'Exam contains invalid, archived, or unauthorized questions';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_exam_questions_security
BEFORE INSERT OR UPDATE OF question_ids ON public.exam_records
FOR EACH ROW EXECUTE FUNCTION public.validate_exam_question_security();

-- ============================================
-- 7. 预置全局数据 (Seed Data)
-- ============================================
-- 初始化高频使用的全局学科和标签 (user_id IS NULL)
INSERT INTO public.subjects (name, color, user_id) VALUES 
('数学', '#4caf50', NULL), 
('英语', '#3f51b5', NULL), 
('语文', '#f44336', NULL)
-- [P0-1 FIX] 谓词补齐，匹配唯一索引
ON CONFLICT (name) WHERE user_id IS NULL AND deleted_at IS NULL DO NOTHING;

INSERT INTO public.tags (name, color, user_id) VALUES 
('重要', '#ff9800', NULL), 
('易错', '#e91e63', NULL), 
('基础', '#2196f3', NULL),
('高频考点', '#f44336', NULL)
-- [P0-1 FIX] 谓词补齐，匹配唯一索引
ON CONFLICT (name) WHERE user_id IS NULL AND deleted_at IS NULL DO NOTHING;

-- [P1-FIX] 预置全局默认 review_settings (新用户默认配置)
-- 必须存在一行 user_id IS NULL 作为全局默认
INSERT INTO public.review_settings (
    user_id, 
    request_retention, 
    maximum_interval, 
    enable_fuzz, 
    timezone, 
    rollover_hour,
    weights
) VALUES (
    NULL,  -- 全局默认
    0.9,   -- 90% 保留率
    365,   -- 最大间隔
    true,  -- 启用随机模糊
    'UTC', -- 默认时区
    4,     -- 凌晨4点日切换
    '[0.212,1.2931,2.3065,8.2956,6.4133,0.8334,3.0194,0.001,1.8722,0.1666,0.796,1.4835,0.0614,0.2629,1.6483,0.6014,1.8729,0.5425,0.0912,0.0658,0.1542]'::jsonb
)
ON CONFLICT ((user_id IS NULL)) WHERE user_id IS NULL DO NOTHING;


-- [V5.9] Helper: Check for updates (Diff View 1.0)
CREATE OR REPLACE FUNCTION public.check_fork_status(p_question_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_child public.error_questions%ROWTYPE;
  v_parent public.error_questions%ROWTYPE;
BEGIN
  SELECT * INTO v_child FROM public.error_questions WHERE id = p_question_id AND user_id = (SELECT auth.uid());
  IF NOT FOUND THEN RAISE EXCEPTION 'Question not found'; END IF;

  IF v_child.forked_from IS NULL THEN
    RETURN jsonb_build_object('is_fork', false);
  END IF;

  SELECT * INTO v_parent FROM public.error_questions WHERE id = v_child.forked_from;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('is_fork', true, 'parent_deleted', true);
  END IF;

  RETURN jsonb_build_object(
    'is_fork', true,
    'has_update', (v_parent.content_hash IS DISTINCT FROM v_child.last_synced_hash),
    'parent_hash', v_parent.content_hash,
    'last_synced_hash', v_child.last_synced_hash,
    -- Simple field diff for UI
    'diff_summary', jsonb_build_object(
       'title_changed', (v_parent.title IS DISTINCT FROM v_child.title),
       'content_changed', (v_parent.content IS DISTINCT FROM v_child.content),
       'answer_changed', (v_parent.correct_answer IS DISTINCT FROM v_child.correct_answer)
    )
  );
END $$;

GRANT EXECUTE ON FUNCTION public.check_fork_status(UUID) TO authenticated;

-- [V5.9] Action: PULL updates from parent
CREATE OR REPLACE FUNCTION public.sync_fork(p_question_id UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  v_uid UUID := (SELECT auth.uid());
  v_child public.error_questions%ROWTYPE;
  v_parent public.error_questions%ROWTYPE;
BEGIN
  SELECT * INTO v_child FROM public.error_questions WHERE id = p_question_id AND user_id = v_uid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Question not found'; END IF;

  IF v_child.forked_from IS NULL THEN RAISE EXCEPTION 'Not a fork'; END IF;

  SELECT * INTO v_parent FROM public.error_questions WHERE id = v_child.forked_from;
  IF NOT FOUND THEN RAISE EXCEPTION 'Source question deleted'; END IF;

  -- Apply Update (Semantic Overwrite)
  UPDATE public.error_questions SET
    title = v_parent.title,
    content = v_parent.content,
    question_type = v_parent.question_type,
    difficulty = v_parent.difficulty,
    correct_answer = v_parent.correct_answer,
    correct_answer_text = v_parent.correct_answer_text,
    explanation = v_parent.explanation,
    image_url = v_parent.image_url,
    hints = v_parent.hints,
    -- Update Sync State
    last_synced_hash = v_parent.content_hash,
    updated_at = now()
  WHERE id = p_question_id;
END $$;

GRANT EXECUTE ON FUNCTION public.sync_fork(UUID) TO authenticated;

-- ============================================
-- 8. 权限收口 (P2-8: Table-Level Permissions)
-- ============================================
-- [P2-8] 确保防御深度：先撤销所有默认权限，再按需最小化授权

-- 8.1 基础表授权
DO $$ 
DECLARE 
  t text;
  tables text[] := ARRAY[
    'subjects', 'tags', 'error_questions', 'error_question_tags', 
    'cards', 'review_logs', 'exam_records', 'import_jobs', 
    'review_settings'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated', t);
    -- 允许已登录用户进行基本操作
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON TABLE public.%I TO service_role', t);
  END LOOP;
END $$;

-- 8.2 只读授权 (P2-1)
REVOKE ALL ON TABLE public.management_logs FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.management_logs TO authenticated;
GRANT ALL ON TABLE public.management_logs TO service_role;

-- 8.2 特殊表授权 (fsrs_configs 正文已有，此处补齐)
REVOKE ALL ON TABLE public.fsrs_configs FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.fsrs_configs TO service_role; -- [V5.4] 权重表仅后端可见

-- 8.3 序列授权 (用于 IDENTITY/SERIAL 字段)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;

-- 8.4 视图授权
REVOKE ALL ON TABLE public.v_due_cards FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.v_due_cards TO authenticated, service_role;

-- ============================================
-- End of Schema V5.9 (Production Hardened & Audit Ready)
-- ============================================
